name: Laravel Test CI
on:
  push:
    branches:
      - master

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Copy .ENV
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"

      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist

      - name: NPM Dependencies
        run: npm install

      - name: NPM Build
        run: npm run build

      - name: Generate APP Key
        run: php artisan key:generate

      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache

      - name: Create Database file
        run: touch database/database.sqlite

      - name: Run migration
        run: php artisan migrate

      - name: Run tests
        env:
          DB_CONNECTION: sqlite
        run: php artisan test






        
